import { createSlice } from '@reduxjs/toolkit';
import axios from 'axios';
const SET_PRODUCTS = 'SET_PRODUCTS';

const productSlice = createSlice({
    name: 'products',
    initialState: {
        products: [],
    },
    reducers: {
        setProducts(state, action) {
            state.products = action.payload;
        },
    },
});

export const { setProducts } = productSlice.actions;

export const fetchProducts = () => async (dispatch) => {
    // Commented out actual API call
    // const response = await axios.get('http://localhost:5000/products');
    // dispatch(setProducts(response.data));

    // Using mock data
    const products = [
        {
                  "company": "NIKE",
                  "country": "USA",
                  "id": 1,
                  "productName": "Nike Dunk Low",
                  "articleNo": "FZ4349-100",
                  "division": "Women",
                  "category": "Shoes",
                  "subCategory": "Lifestyle",
                  "listPrice": 130,
                  "salePrice": null,
                  "currency": "USD",
                  "description": "Created for the hardwood but taken to the streets, this '80s basketball icon returns with classic details and throwback hoops flair. Synthetic leather overlays help the Nike Dunk channel vintage style while its padded, low-cut collar lets you take your game anywhere—in comfort.",
                  "url": "https://nike.com/us/t/dunk-low-womens-shoes-KxSmbV/FZ4349-100",
                  "imageUrl": "https://static.nike.com/a/images/t_default/ac89cfe2-a425-41b4-b51a-facde9df1215/dunk-low-womens-shoes-KxSmbV.png"
                },{
                  "company": "NIKE",
                  "country": "USA",
                  "id": 2,
                  "productName": "Nike Killshot 2 Leather",
                  "articleNo": "432997-111",
                  "division": "Men",
                  "category": "Shoes",
                  "subCategory": "Lifestyle",
                  "listPrice": 90,
                  "salePrice": null,
                  "currency": "USD",
                  "description": "Inspired by the original low-profile tennis shoes, the Nike Killshot 2 updates the upper with various textured leathers to create a fresh look. From soft suedes to smooth leathers with the perfect sheen, it's courtside attitude with a modern touch. To prove you're on top, the rubber gum sole adds the cherry on bottom.",
                  "url": "https://nike.com/us/t/killshot-2-leather-mens-shoes-72M7D1/432997-111",
                  "imageUrl": "https://static.nike.com/a/images/t_default/af5dcd77-81d6-48b7-8223-4805cf98100b/killshot-2-leather-mens-shoes-72M7D1.png"
                },{
                  "company": "NIKE",
                  "country": "USA",
                  "id": 3,
                  "productName": "Nike Air Max SC",
                  "articleNo": "CW4554-119",
                  "division": "Women",
                  "category": "Shoes",
                  "subCategory": "Lifestyle",
                  "listPrice": 90,
                  "salePrice": null,
                  "currency": "USD",
                  "description": "With its easy going lines, heritage track look and of course, visible Air cushioning, the Nike Air Max SC is the perfect finish to any outfit. The rich mixture of materials adds depth while making it a durable and lightweight shoe for everyday wear.",
                  "url": "https://nike.com/us/t/air-max-sc-womens-shoes-CwMCK7/CW4554-119",
                  "imageUrl": "https://static.nike.com/a/images/t_default/3345faeb-5949-49af-89b2-cbff4adcb4b8/air-max-sc-womens-shoes-CwMCK7.png"
                },{
                  "company": "NIKE",
                  "country": "USA",
                  "productName": "Nike Calm",
                  "articleNo": "FD4116-201",
                  "division": "Men",
                  "category": "Shoes",
                  "subCategory": "Lifestyle",
                  "listPrice": 50,
                  "salePrice": null,
                  "currency": "USD",
                  "description": "Enjoy a calm, comfortable experience—no matter where your day off takes you. Made with soft yet responsive foam, these lightweight slides are easy to style and easy to pack. While the water-friendly design makes them ideal for the beach or pool, the minimalist look is elevated enough to wear around in the city. Time to slide in and check out.",
                  "url": "https://nike.com/us/t/calm-mens-slides-4hQGBf/FD4116-201",
                  "imageUrl": "https://static.nike.com/a/images/t_default/18da855d-351f-4fc5-82bd-74fc40bd3f40/calm-mens-slides-4hQGBf.png"
                },{
                  "company": "NIKE",
                  "country": "USA",
                  "id": 4,
                  "productName": "Nike Mercurial Superfly 9 Pro",
                  "articleNo": "DJ5598-040",
                  "division": "Unisex",
                  "category": "Shoes",
                  "subCategory": "Soccer",
                  "listPrice": 170,
                  "salePrice": 144.97,
                  "currency": "USD",
                  "description": "Instantly tilt the field in the bold design of the Superfly 9 Pro FG. It's loaded with a Zoom Air unit, so you can dominate in the waning minutes of a match—when it matters most. Fast is in the Air.",
                  "url": "https://nike.com/us/t/mercurial-superfly-9-pro-firm-ground-high-top-soccer-cleats-lpGlgb/DJ5598-040",
                  "imageUrl": "https://static.nike.com/a/images/t_default/7d909b37-b82b-47ca-b1db-a149cf3a9529/mercurial-superfly-9-pro-firm-ground-high-top-soccer-cleats-lpGlgb.png"
                },
                {
                  "company": "NIKE",
                  "country": "USA",
                  "productName": "Nike Calm",
                  "articleNo": "FD4116-400",
                  "division": "Men",
                  "category": "Shoes",
                  "subCategory": "Swimming",
                  "listPrice": 50,
                  "salePrice": null,
                  "currency": "USD",
                  "description": "Enjoy a calm, comfortable experience—no matter where your day off takes you. Made with soft yet responsive foam, these lightweight slides are easy to style and easy to pack. While the water-friendly design makes them ideal for the beach or pool, the minimalist look is elevated enough to wear around in the city. Time to slide in and check out.",
                  "url": "https://nike.com/us/t/calm-mens-slides-4hQGBf/FD4116-400",
                  "imageUrl": "https://static.nike.com/a/images/t_default/62346412-6ce0-44c7-af46-1c404353d545/calm-mens-slides-4hQGBf.png"
                },{
              
                  "company": "NIKE",
                  "country": "USA",
                  "id": 5,
                  "productName": "Nike Mercurial Superfly 9 Pro",
                  "articleNo": "DJ5598-700",
                  "division": "Unisex",
                  "category": "Shoes",
                  "subCategory": "Soccer",
                  "listPrice": 170,
                  "salePrice": 149.97,
                  "currency": "USD",
                  "description": "Instantly tilt the field in the bold design of the Superfly 9 Pro FG. It's loaded with a Zoom Air unit, so you can dominate in the waning minutes of a match—when it matters most. Fast is in the Air.",
                  "url": "https://nike.com/us/t/mercurial-superfly-9-pro-firm-ground-high-top-soccer-cleats-lpGlgb/DJ5598-700",
                  "imageUrl": "https://static.nike.com/a/images/t_default/31df0425-4bf1-41c8-ba60-b52a9d72b3e4/mercurial-superfly-9-pro-firm-ground-high-top-soccer-cleats-lpGlgb.png"
                },{
                  "company": "NIKE",
                  "country": "USA",
                  "id": 6,
                  "productName": "Tatum 2 \"Sidewalk Chalk\"",
                  "articleNo": "FJ6457-300",
                  "division": "Unisex",
                  "category": "Shoes",
                  "subCategory": "Basketball",
                  "listPrice": 125,
                  "salePrice": null,
                  "currency": "USD",
                  "description": "It's not over until you hear that buzzer. Fly through your game with energy to spare in the Tatum 2. It helps you stay light on your feet by limiting the use of heavy rubber. A full-length Nike Air Strobel unit supports your quick shifts, and a sturdy frame pairs with supportive foam that molds to your feet for a contained feel.",
                  "url": "https://nike.com/us/t/tatum-2-vortex-basketball-shoes-8XGVH8/FJ6457-300",
                  "imageUrl": "https://static.nike.com/a/images/t_default/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/cf805f5a-eab7-46ac-acdc-91d3912744c1/tatum-2-vortex-basketball-shoes-8XGVH8.png"
                },{
                  "company": "NIKE",
                  "country": "USA",
                  "id": 7,
                  "productName": "Nike Free RN 2018",
                  "articleNo": "942837-100",
                  "division": "Women",
                  "category": "Shoes",
                  "subCategory": "Running",
                  "listPrice": 100,
                  "salePrice": 80.97,
                  "currency": "USD",
                  "description": "The Nike Free RN 2018 delivers an even more adaptive fit than before. Stretch material in the upper moves with your foot, while the tri-star outsole pattern adjusts to your every step for a ride that delivers support and flexibility where you need it.",
                  "url": "https://nike.com/us/t/free-rn-2018-womens-running-shoes-zE8Je3/942837-100",
                  "imageUrl": "https://static.nike.com/a/images/t_default/lpedh5gu9bxuvsohuxma/free-rn-2018-womens-running-shoes-zE8Je3.png"
                },{
                  "company": "NIKE",
                  "country": "USA",
                  "id": 8,
                  "productName": "Nike Alphafly 3",
                  "articleNo": "FD8311-700",
                  "division": "Men",
                  "category": "Shoes",
                  "subCategory": "Running",
                  "listPrice": 285,
                  "salePrice": null,
                  "currency": "USD",
                  "description": "Fine-tuned for marathon speed, the Alphafly 3 helps push you beyond what you thought possible. Three innovative technologies power your run: A double dose of Air Zoom units helps launch you into your next step; a full-length carbon fiber plate helps propel you forward with ease; and a heel-to-toe ZoomX foam midsole helps keep you fresh from start to 26.2. Time to leave your old personal records in the dust.",
                  "url": "https://nike.com/us/t/alphafly-3-mens-road-racing-shoes-6Nc43S/FD8311-700",
                  "imageUrl": "https://static.nike.com/a/images/t_default/7776f88c-1bf6-49ac-a53b-b532f4c51a87/alphafly-3-mens-road-racing-shoes-6Nc43S.png"
                },

















                {
                    "company": "NIKE",
                    "country": "USA",
                    "id": 9,
                    "productName": "Jordan Jumpman",
                    "articleNo": "DC7485-349",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Lifestyle",
                    "listPrice": 32,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "Rise and shine in this classic tee from Jordan Brand. Made from soft, comfortable cotton, it features a clean, classic Jumpman that's embroidered on the chest.",
                    "url": "https://nike.com/us/t/jordan-jumpman-mens-short-sleeve-t-shirt-qwkX7c/DC7485-349",
                    "imageUrl": "https://static.nike.com/a/images/t_default/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/ae95a61a-7031-4ef2-abd5-f417ec997cf8/jordan-jumpman-mens-short-sleeve-t-shirt-qwkX7c.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Jordan Jumpman",
                    "articleNo": "DC7485-410",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Lifestyle",
                    "listPrice": 32.5,
                    "salePrice": 19.97,
                    "currency": "USD",
                    "description": "Rise and shine in this classic tee from Jordan Brand. Made from soft, comfortable cotton, it features a clean, classic Jumpman that's embroidered on the chest.",
                    "url": "https://nike.com/us/t/jordan-jumpman-mens-short-sleeve-t-shirt-qwkX7c/DC7485-410",
                    "imageUrl": "https://static.nike.com/a/images/t_default/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/429aaae4-7b7b-4691-86bc-4d7f01511701/jordan-jumpman-mens-short-sleeve-t-shirt-qwkX7c.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Jordan Jumpman",
                    "articleNo": "DC7485-091",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Lifestyle",
                    "listPrice": 32,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "Rise and shine in this classic tee from Jordan Brand. Made from soft, comfortable cotton, it features a clean, classic Jumpman that's embroidered on the chest.",
                    "url": "https://nike.com/us/t/jordan-jumpman-mens-short-sleeve-t-shirt-qwkX7c/DC7485-091",
                    "imageUrl": "https://static.nike.com/a/images/t_default/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/2a80a079-0b24-4dfa-890b-c453e72f4528/jordan-jumpman-mens-short-sleeve-t-shirt-qwkX7c.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Jordan Jumpman",
                    "articleNo": "DC7485-010",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Lifestyle",
                    "listPrice": 32,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "Rise and shine in this classic tee from Jordan Brand. Made from soft, comfortable cotton, it features a clean, classic Jumpman that's embroidered on the chest.",
                    "url": "https://nike.com/us/t/jordan-jumpman-mens-short-sleeve-t-shirt-qwkX7c/DC7485-010",
                    "imageUrl": "https://static.nike.com/a/images/t_default/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/f3be75d2-617d-4925-936e-c401674144f5/jordan-jumpman-mens-short-sleeve-t-shirt-qwkX7c.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Jordan Jumpman",
                    "articleNo": "DC7485-100",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Lifestyle",
                    "listPrice": 32,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "Rise and shine in this classic tee from Jordan Brand. Made from soft, comfortable cotton, it features a clean, classic Jumpman that's embroidered on the chest.",
                    "url": "https://nike.com/us/t/jordan-jumpman-mens-short-sleeve-t-shirt-qwkX7c/DC7485-100",
                    "imageUrl": "https://static.nike.com/a/images/t_default/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/6f872eb7-5b29-489b-a88d-a197772ec263/jordan-jumpman-mens-short-sleeve-t-shirt-qwkX7c.png"
                  },
              
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike Sportswear",
                    "articleNo": "FZ4720-060",
                    "division": "Kids",
                    "category": "Clothing",
                    "subCategory": "Lifestyle",
                    "listPrice": 50,
                    "salePrice": 29.97,
                    "currency": "USD",
                    "description": "Varsity-inspired style meets modern comfort in these cozy joggers. Made with lightweight fleece, they're smooth on the outside and brushed soft on the inside for an easy layer for when you want extra warmth.",
                    "url": "https://nike.com/us/t/sportswear-big-kids-girls-oversized-fleece-pants-HgLSHB/FZ4720-060",
                    "imageUrl": "https://static.nike.com/a/images/t_default/3fb8651f-c65b-4ea4-8e59-6353f16e7d00/sportswear-big-kids-girls-oversized-fleece-pants-HgLSHB.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Crystal Dunn USWNT",
                    "articleNo": "W11942474W-RAP",
                    "division": "Women",
                    "category": "Clothing",
                    "subCategory": "Basketball",
                    "listPrice": 35,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "This classic cotton tee is the perfect piece for cheering on Crystal Dunn as she competes at the biggest stage in soccer.",
                    "url": "https://nike.com/us/t/megan-rapinoe-uswnt-womens-soccer-t-shirt-rzF4hX/W11942474W-RAP",
                    "imageUrl": "https://static.nike.com/a/images/t_default/3a67976b-75b0-4314-bc66-44e0d59c0d64/megan-rapinoe-uswnt-womens-soccer-t-shirt-rzF4hX.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Crystal Dunn USWNT",
                    "articleNo": "W11942474W-LAV",
                    "division": "Women",
                    "category": "Clothing",
                    "subCategory": "Basketball",
                    "listPrice": 35,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "This classic cotton tee is the perfect piece for cheering on Crystal Dunn as she competes at the biggest stage in soccer.",
                    "url": "https://nike.com/us/t/rose-lavelle-uswnt-womens-soccer-t-shirt-rzF4hX/W11942474W-LAV",
                    "imageUrl": "https://static.nike.com/a/images/t_default/08c3b5a5-6b28-4256-a159-2d8be8eff09e/rose-lavelle-uswnt-womens-soccer-t-shirt-rzF4hX.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Crystal Dunn USWNT",
                    "articleNo": "W11942474W-SMI",
                    "division": "Women",
                    "category": "Clothing",
                    "subCategory": "Basketball",
                    "listPrice": 35,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "This classic cotton tee is the perfect piece for cheering on Crystal Dunn as she competes at the biggest stage in soccer.",
                    "url": "https://nike.com/us/t/sophia-smith-uswnt-womens-soccer-t-shirt-rzF4hX/W11942474W-SMI",
                    "imageUrl": "https://static.nike.com/a/images/t_default/2f691d8b-faf3-4c3d-9902-e4c47baf4710/sophia-smith-uswnt-womens-soccer-t-shirt-rzF4hX.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Crystal Dunn USWNT",
                    "articleNo": "W11942474W-MOR",
                    "division": "Women",
                    "category": "Clothing",
                    "subCategory": "Basketball",
                    "listPrice": 35,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "This classic cotton tee is the perfect piece for cheering on Crystal Dunn as she competes at the biggest stage in soccer.",
                    "url": "https://nike.com/us/t/alex-morgan-uswnt-womens-soccer-t-shirt-rzF4hX/W11942474W-MOR",
                    "imageUrl": "https://static.nike.com/a/images/t_default/129440cb-1f1f-4196-8cdb-33aa8bba7b20/alex-morgan-uswnt-womens-soccer-t-shirt-rzF4hX.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Bo Jackson Chicago White Sox City Connect",
                    "articleNo": "T7LMRXCCQA2-C2Q",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 175,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "Inspired by the on-field uniforms of the Chicago White Sox, this Bo Jackson City Connect Jersey delivers an authentic look with twill details that display pride for your team’s home. The sweat-wicking, double-knit mesh fabric helps provide a breathable, comfortable feel on game day.",
                    "url": "https://nike.com/us/t/bo-jackson-chicago-white-sox-city-connect-mens-dri-fit-adv-ndZfrT/T7LMRXCCQA2-C2Q",
                    "imageUrl": "https://static.nike.com/a/images/t_default/96d22d02-d296-47e0-bfec-cbfacf82f459/bo-jackson-chicago-white-sox-city-connect-mens-dri-fit-adv-ndZfrT.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Alabama",
                    "articleNo": "C16835C17-ALA",
                    "division": "Unisex",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 35,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "There's no better way to celebrate America's pastime than going to the ballpark. Feel the spring breeze as you munch on a hot dog and watch your favorite Crimson Tide player round 3rd in the 9th. Keep your eyes on the play and revel in a successful run in this fitted high-crown hat. Its Alabama details give a nod to the team you love.",
                    "url": "https://nike.com/us/t/alabamafitted-baseball-hat-7JkN7t/C16835C17-ALA",
                    "imageUrl": "https://static.nike.com/a/images/t_default/6011a053-447a-488c-90d6-625b8f905201/alabamafitted-baseball-hat-7JkN7t.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Alabama",
                    "articleNo": "C16835C17-FSU",
                    "division": "Unisex",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 35,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "There's no better way to celebrate America's pastime than going to the ballpark. Feel the spring breeze as you munch on a hot dog and watch your favorite Crimson Tide player round 3rd in the 9th. Keep your eyes on the play and revel in a successful run in this fitted high-crown hat. Its Alabama details give a nod to the team you love.",
                    "url": "https://nike.com/us/t/florida-statefitted-baseball-hat-7JkN7t/C16835C17-FSU",
                    "imageUrl": "https://static.nike.com/a/images/t_default/1d14902f-24af-45e9-a336-7bfc8b1ddf9e/florida-statefitted-baseball-hat-7JkN7t.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Alabama",
                    "articleNo": "C16835C17-OHI",
                    "division": "Unisex",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 35,
                    "salePrice": 28.97,
                    "currency": "USD",
                    "description": "There's no better way to celebrate America's pastime than going to the ballpark. Feel the spring breeze as you munch on a hot dog and watch your favorite Crimson Tide player round 3rd in the 9th. Keep your eyes on the play and revel in a successful run in this fitted high-crown hat. Its Alabama details give a nod to the team you love.",
                    "url": "https://nike.com/us/t/ohio-statefitted-baseball-hat-7JkN7t/C16835C17-OHI",
                    "imageUrl": "https://static.nike.com/a/images/t_default/8b3df121-594f-4383-94de-9e00387405e0/ohio-statefitted-baseball-hat-7JkN7t.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Alabama",
                    "articleNo": "C16835C17-ORS",
                    "division": "Unisex",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 35,
                    "salePrice": 26.97,
                    "currency": "USD",
                    "description": "There's no better way to celebrate America's pastime than going to the ballpark. Feel the spring breeze as you munch on a hot dog and watch your favorite Crimson Tide player round 3rd in the 9th. Keep your eyes on the play and revel in a successful run in this fitted high-crown hat. Its Alabama details give a nod to the team you love.",
                    "url": "https://nike.com/us/t/oregon-statefitted-baseball-hat-7JkN7t/C16835C17-ORS",
                    "imageUrl": "https://static.nike.com/a/images/t_default/3f5b171f-5deb-420f-bb90-e0f5afb8035b/oregon-statefitted-baseball-hat-7JkN7t.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Alabama",
                    "articleNo": "C16835C17-KEN",
                    "division": "Unisex",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 35,
                    "salePrice": 26.97,
                    "currency": "USD",
                    "description": "There's no better way to celebrate America's pastime than going to the ballpark. Feel the spring breeze as you munch on a hot dog and watch your favorite Crimson Tide player round 3rd in the 9th. Keep your eyes on the play and revel in a successful run in this fitted high-crown hat. Its Alabama details give a nod to the team you love.",
                    "url": "https://nike.com/us/t/kentuckyfitted-baseball-hat-7JkN7t/C16835C17-KEN",
                    "imageUrl": "https://static.nike.com/a/images/t_default/8c2ae5fa-1a9c-471a-b8a6-4e91aadfc1f8/kentuckyfitted-baseball-hat-7JkN7t.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Alabama",
                    "articleNo": "C16835C17-CLM",
                    "division": "Unisex",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 35,
                    "salePrice": 26.97,
                    "currency": "USD",
                    "description": "There's no better way to celebrate America's pastime than going to the ballpark. Feel the spring breeze as you munch on a hot dog and watch your favorite Crimson Tide player round 3rd in the 9th. Keep your eyes on the play and revel in a successful run in this fitted high-crown hat. Its Alabama details give a nod to the team you love.",
                    "url": "https://nike.com/us/t/clemsonfitted-baseball-hat-7JkN7t/C16835C17-CLM",
                    "imageUrl": "https://static.nike.com/a/images/t_default/c13a188c-beab-4b08-89f8-e1578be2fa26/clemsonfitted-baseball-hat-7JkN7t.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Alabama",
                    "articleNo": "C16835C17-FLO",
                    "division": "Unisex",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 35,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "There's no better way to celebrate America's pastime than going to the ballpark. Feel the spring breeze as you munch on a hot dog and watch your favorite Crimson Tide player round 3rd in the 9th. Keep your eyes on the play and revel in a successful run in this fitted high-crown hat. Its Alabama details give a nod to the team you love.",
                    "url": "https://nike.com/us/t/floridafitted-baseball-hat-7JkN7t/C16835C17-FLO",
                    "imageUrl": "https://static.nike.com/a/images/t_default/d707296e-1ce3-46e7-92eb-e2ae1b067131/floridafitted-baseball-hat-7JkN7t.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Alabama",
                    "articleNo": "C16835C17-OKS",
                    "division": "Unisex",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 35,
                    "salePrice": 27.97,
                    "currency": "USD",
                    "description": "There's no better way to celebrate America's pastime than going to the ballpark. Feel the spring breeze as you munch on a hot dog and watch your favorite Crimson Tide player round 3rd in the 9th. Keep your eyes on the play and revel in a successful run in this fitted high-crown hat. Its Alabama details give a nod to the team you love.",
                    "url": "https://nike.com/us/t/oklahoma-statefitted-baseball-hat-7JkN7t/C16835C17-OKS",
                    "imageUrl": "https://static.nike.com/a/images/t_default/cdf5ba51-14b5-4223-8bbb-11a5da69e362/oklahoma-statefitted-baseball-hat-7JkN7t.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Alabama",
                    "articleNo": "C16835C20-USC",
                    "division": "Unisex",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 35,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "There's no better way to celebrate America's pastime than going to the ballpark. Feel the spring breeze as you munch on a hot dog and watch your favorite Crimson Tide player round 3rd in the 9th. Keep your eyes on the play and revel in a successful run in this fitted high-crown hat. Its Alabama details give a nod to the team you love.",
                    "url": "https://nike.com/us/t/uscfitted-baseball-hat-7JkN7t/C16835C20-USC",
                    "imageUrl": "https://static.nike.com/a/images/t_default/3847058c-6d7b-4543-a2f9-1909a89b2d09/uscfitted-baseball-hat-7JkN7t.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Alabama",
                    "articleNo": "C16835C17-DUK",
                    "division": "Unisex",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 35,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "There's no better way to celebrate America's pastime than going to the ballpark. Feel the spring breeze as you munch on a hot dog and watch your favorite Crimson Tide player round 3rd in the 9th. Keep your eyes on the play and revel in a successful run in this fitted high-crown hat. Its Alabama details give a nod to the team you love.",
                    "url": "https://nike.com/us/t/dukefitted-baseball-hat-7JkN7t/C16835C17-DUK",
                    "imageUrl": "https://static.nike.com/a/images/t_default/988c6703-10e1-47c6-98f8-58550bcd7f1e/dukefitted-baseball-hat-7JkN7t.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Alabama",
                    "articleNo": "C16835C17-GEO",
                    "division": "Unisex",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 35,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "There's no better way to celebrate America's pastime than going to the ballpark. Feel the spring breeze as you munch on a hot dog and watch your favorite Crimson Tide player round 3rd in the 9th. Keep your eyes on the play and revel in a successful run in this fitted high-crown hat. Its Alabama details give a nod to the team you love.",
                    "url": "https://nike.com/us/t/georgiafitted-baseball-hat-7JkN7t/C16835C17-GEO",
                    "imageUrl": "https://static.nike.com/a/images/t_default/6babd9ef-3cae-4e16-afc7-30f3b072ff95/georgiafitted-baseball-hat-7JkN7t.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Alabama",
                    "articleNo": "C16835C17-OLM",
                    "division": "Unisex",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 35,
                    "salePrice": 26.97,
                    "currency": "USD",
                    "description": "There's no better way to celebrate America's pastime than going to the ballpark. Feel the spring breeze as you munch on a hot dog and watch your favorite Crimson Tide player round 3rd in the 9th. Keep your eyes on the play and revel in a successful run in this fitted high-crown hat. Its Alabama details give a nod to the team you love.",
                    "url": "https://nike.com/us/t/ole-missfitted-baseball-hat-7JkN7t/C16835C17-OLM",
                    "imageUrl": "https://static.nike.com/a/images/t_default/493f0e10-d2f3-4e23-85ed-179c031c9e35/ole-missfitted-baseball-hat-7JkN7t.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Alabama",
                    "articleNo": "C16835C17-MSU",
                    "division": "Unisex",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 35,
                    "salePrice": 26.97,
                    "currency": "USD",
                    "description": "There's no better way to celebrate America's pastime than going to the ballpark. Feel the spring breeze as you munch on a hot dog and watch your favorite Crimson Tide player round 3rd in the 9th. Keep your eyes on the play and revel in a successful run in this fitted high-crown hat. Its Alabama details give a nod to the team you love.",
                    "url": "https://nike.com/us/t/michigan-statefitted-baseball-hat-7JkN7t/C16835C17-MSU",
                    "imageUrl": "https://static.nike.com/a/images/t_default/227d9b3f-f93b-4f71-87d2-8eb2529389ed/michigan-statefitted-baseball-hat-7JkN7t.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Alabama",
                    "articleNo": "C16835C17-ARK",
                    "division": "Unisex",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 35,
                    "salePrice": 26.97,
                    "currency": "USD",
                    "description": "There's no better way to celebrate America's pastime than going to the ballpark. Feel the spring breeze as you munch on a hot dog and watch your favorite Crimson Tide player round 3rd in the 9th. Keep your eyes on the play and revel in a successful run in this fitted high-crown hat. Its Alabama details give a nod to the team you love.",
                    "url": "https://nike.com/us/t/arkansasfitted-baseball-hat-7JkN7t/C16835C17-ARK",
                    "imageUrl": "https://static.nike.com/a/images/t_default/27c1885c-b4e3-412a-9d29-a37332dbf116/arkansasfitted-baseball-hat-7JkN7t.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Alabama",
                    "articleNo": "C16835C17-ARI",
                    "division": "Unisex",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 35,
                    "salePrice": 26.97,
                    "currency": "USD",
                    "description": "There's no better way to celebrate America's pastime than going to the ballpark. Feel the spring breeze as you munch on a hot dog and watch your favorite Crimson Tide player round 3rd in the 9th. Keep your eyes on the play and revel in a successful run in this fitted high-crown hat. Its Alabama details give a nod to the team you love.",
                    "url": "https://nike.com/us/t/arizonafitted-baseball-hat-7JkN7t/C16835C17-ARI",
                    "imageUrl": "https://static.nike.com/a/images/t_default/925a5366-aa07-4996-8cc4-07610d29654d/arizonafitted-baseball-hat-7JkN7t.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike ACG Lowcate",
                    "articleNo": "DM8019-002",
                    "division": "Men",
                    "category": "Shoes",
                    "subCategory": "Hiking",
                    "listPrice": 110,
                    "salePrice": 82.97,
                    "currency": "USD",
                    "description": "From streets to parks to trails, build up the miles in these city-to-adventure shoes. Designed and tested in the rugged Pacific Northwest, the mixed-material upper pairs durability with easy styling. A rubber outsole with a heavy-duty, tuned lug pattern grips slick and rocky terrain so you can go up, down, through and around.",
                    "url": "https://nike.com/us/t/acg-lowcate-shoes-7Px0Lq/DM8019-002",
                    "imageUrl": "https://static.nike.com/a/images/t_default/98e24f31-a9cc-449f-8774-f067ffd8c7fb/acg-lowcate-shoes-7Px0Lq.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike ACG Lowcate",
                    "articleNo": "DR1030-001",
                    "division": "Men",
                    "category": "Shoes",
                    "subCategory": "Lifestyle",
                    "listPrice": 120,
                    "salePrice": 66.97,
                    "currency": "USD",
                    "description": "From streets to parks to trails, build up the miles in these city-to-adventure shoes. Designed and tested in the rugged Pacific Northwest, the mixed-material upper pairs durability with easy styling. A rubber outsole with a heavy-duty, tuned lug pattern grips slick and rocky terrain so you can go up, down, through and around.",
                    "url": "https://nike.com/us/t/acg-lowcate-se-mens-shoes-7Px0Lq/DR1030-001",
                    "imageUrl": "https://static.nike.com/a/images/t_default/e06535f6-e87e-48fd-b134-ffe9375705e5/acg-lowcate-se-mens-shoes-7Px0Lq.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike ACG Lowcate",
                    "articleNo": "DX2256-002",
                    "division": "Men",
                    "category": "Shoes",
                    "subCategory": "Hiking",
                    "listPrice": 115,
                    "salePrice": 80.97,
                    "currency": "USD",
                    "description": "From streets to parks to trails, build up the miles in these city-to-adventure shoes. Designed and tested in the rugged Pacific Northwest, the mixed-material upper pairs durability with easy styling. A rubber outsole with a heavy-duty, tuned lug pattern grips slick and rocky terrain so you can go up, down, through and around.",
                    "url": "https://nike.com/us/t/acg-lowcate-mens-shoes-7Px0Lq/DX2256-002",
                    "imageUrl": "https://static.nike.com/a/images/t_default/e6aae508-dac9-4d9c-afac-4ec7890dd077/acg-lowcate-mens-shoes-7Px0Lq.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "San Diego Padres Team Swoosh Lockup",
                    "articleNo": "N19979QPYP-YK1",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 35,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "This Team Swoosh Lockup T-Shirt helps you show loyalty to the San Diego Padres with bold graphics on the front. It’s made from soft cotton fabric for a comfortable feel on game day.",
                    "url": "https://nike.com/us/t/san-diego-padres-team-swoosh-lockup-mens-t-shirt-QSPDvR/N19979QPYP-YK1",
                    "imageUrl": "https://static.nike.com/a/images/t_default/18b34ae8-6dcd-431b-8dac-872a1519cc62/san-diego-padres-team-swoosh-lockup-mens-t-shirt-QSPDvR.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike Session",
                    "articleNo": "NKHF0156-278",
                    "division": "Men",
                    "category": "Accessories",
                    "subCategory": "Lifestyle",
                    "listPrice": 99,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "The Nike Blue Light Collection features a premium lens coating that helps reduce blue light exposure for use at home, office, and gaming on your digital devices.",
                    "url": "https://nike.com/us/t/session-blue-light-glasses-GgHSXJ/NKHF0156-278",
                    "imageUrl": "https://static.nike.com/a/images/t_default/eba5bc25-5824-45c8-8ae9-afcf8780ac36/session-blue-light-glasses-GgHSXJ.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike Session",
                    "articleNo": "NKHF0156-021",
                    "division": "Men",
                    "category": "Accessories",
                    "subCategory": "Lifestyle",
                    "listPrice": 99,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "The Nike Blue Light Collection features a premium lens coating that helps reduce blue light exposure for use at home, office, and gaming on your digital devices.",
                    "url": "https://nike.com/us/t/session-blue-light-glasses-GgHSXJ/NKHF0156-021",
                    "imageUrl": "https://static.nike.com/a/images/t_default/ab243453-e3cc-4de7-9a75-c30a23ff005f/session-blue-light-glasses-GgHSXJ.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike Session",
                    "articleNo": "NKHF0156-010",
                    "division": "Men",
                    "category": "Accessories",
                    "subCategory": "Lifestyle",
                    "listPrice": 99,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "The Nike Blue Light Collection features a premium lens coating that helps reduce blue light exposure for use at home, office, and gaming on your digital devices.",
                    "url": "https://nike.com/us/t/session-blue-light-glasses-GgHSXJ/NKHF0156-010",
                    "imageUrl": "https://static.nike.com/a/images/t_default/85bfd9f0-534b-473d-a8c0-4ae1aa40da27/session-blue-light-glasses-GgHSXJ.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike",
                    "articleNo": "5ND369-023",
                    "division": "Kids",
                    "category": "Clothing",
                    "subCategory": "Lifestyle",
                    "listPrice": 22,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "Dress the littlest athletes for the futura in this comfy all-in-1, made of soft cotton jersey knit fabric that feels gentle on baby's skin. This romper is roomy enough to layer over a sleeveless bodysuit for extra warmth and snappy tape closures at the shoulder and inseam make changing and dressing easy.",
                    "url": "https://nike.com/us/t/baby-0-9m-futura-romper-d3RgKt/5ND369-023",
                    "imageUrl": "https://static.nike.com/a/images/t_default/qfn0nso3rdrwq2ulb1m3/baby-0-9m-futura-romper-d3RgKt.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike",
                    "articleNo": "N1009017-008",
                    "division": "Unisex",
                    "category": "Accessories",
                    "subCategory": "Yoga",
                    "listPrice": 24,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "Find a new level of flow. This lightweight EVA foam block helps extend your reach or add a touch of support where you feel you need it. Plus, its portability makes it ideal for travel or classes at your local studio.",
                    "url": "https://nike.com/us/t/yoga-block-hWggCh/N1009017-008",
                    "imageUrl": "https://static.nike.com/a/images/t_default/a299700f-d446-4b92-a56e-7bfecb468ba1/yoga-block-hWggCh.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike Sportswear",
                    "articleNo": "FZ4720-227",
                    "division": "Kids",
                    "category": "Clothing",
                    "subCategory": "Lifestyle",
                    "listPrice": 50,
                    "salePrice": 29.97,
                    "currency": "USD",
                    "description": "Varsity-inspired style meets modern comfort in these cozy joggers. Made with lightweight fleece, they're smooth on the outside and brushed soft on the inside for an easy layer for when you want extra warmth.",
                    "url": "https://nike.com/us/t/sportswear-big-kids-girls-oversized-fleece-pants-HgLSHB/FZ4720-227",
                    "imageUrl": "https://static.nike.com/a/images/t_default/7e1f74c5-b1e3-4e06-9297-092a5a26abc8/sportswear-big-kids-girls-oversized-fleece-pants-HgLSHB.png"
                  },
               
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Air Jordan",
                    "articleNo": "NJ0313-001",
                    "division": "Kids",
                    "category": "Clothing",
                    "subCategory": "Lifestyle",
                    "listPrice": 50,
                    "salePrice": 35.97,
                    "currency": "USD",
                    "description": "The Air Jordan Set includes a short-sleeve bodysuit, beanie, booties and a handy changing blanket featuring coordinated designs on soft knit fabric for all-day, cozy comfort.",
                    "url": "https://nike.com/us/t/air-jordan-baby-bodysuit-beanie-booties-and-blanket-set-tD7fgS/NJ0313-001",
                    "imageUrl": "https://static.nike.com/a/images/t_default/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/a01d817e-45aa-40bf-9f1e-9c3756c0297d/air-jordan-baby-bodysuit-beanie-booties-and-blanket-set-tD7fgS.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Rafa",
                    "articleNo": "FV8436-480",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Tennis",
                    "listPrice": 40,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "He's the King of Clay, a multi-time champion and a tennis legend. Rep one of the best ever with this relaxed fit Rafa tee, designed with sweat-wicking fabric to help you stay dry on the court and beyond.",
                    "url": "https://nike.com/us/t/rafa-mens-nikecourt-dri-fit-tennis-t-shirt-bbK1ld/FV8436-480",
                    "imageUrl": "https://static.nike.com/a/images/t_default/52313585-0334-414e-8e6b-27302c8f64fd/rafa-mens-nikecourt-dri-fit-tennis-t-shirt-bbK1ld.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Rafa",
                    "articleNo": "FV8436-010",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Tennis",
                    "listPrice": 40,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "He's the King of Clay, a multi-time champion and a tennis legend. Rep one of the best ever with this relaxed fit Rafa tee, designed with sweat-wicking fabric to help you stay dry on the court and beyond.",
                    "url": "https://nike.com/us/t/rafa-mens-nikecourt-dri-fit-tennis-t-shirt-bbK1ld/FV8436-010",
                    "imageUrl": "https://static.nike.com/a/images/t_default/1b9a94f0-9b0b-4a98-be77-63934ce48ce0/rafa-mens-nikecourt-dri-fit-tennis-t-shirt-bbK1ld.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Rafa",
                    "articleNo": "FV8436-100",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Tennis",
                    "listPrice": 40,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "He's the King of Clay, a multi-time champion and a tennis legend. Rep one of the best ever with this relaxed fit Rafa tee, designed with sweat-wicking fabric to help you stay dry on the court and beyond.",
                    "url": "https://nike.com/us/t/rafa-mens-nikecourt-dri-fit-tennis-t-shirt-bbK1ld/FV8436-100",
                    "imageUrl": "https://static.nike.com/a/images/t_default/fe1a13ba-90a4-47dd-acd8-3f2f59c24e55/rafa-mens-nikecourt-dri-fit-tennis-t-shirt-bbK1ld.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Rafa",
                    "articleNo": "FV8436-394",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Tennis",
                    "listPrice": 40,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "He's the King of Clay, a multi-time champion and a tennis legend. Rep one of the best ever with this relaxed fit Rafa tee, designed with sweat-wicking fabric to help you stay dry on the court and beyond.",
                    "url": "https://nike.com/us/t/rafa-mens-nikecourt-dri-fit-tennis-t-shirt-bbK1ld/FV8436-394",
                    "imageUrl": "https://static.nike.com/a/images/t_default/cb264603-b19b-479d-879a-8b3cbe8fd9e7/rafa-mens-nikecourt-dri-fit-tennis-t-shirt-bbK1ld.png"
                  },
               
                 
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Club América",
                    "articleNo": "DV5184-409",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Soccer",
                    "listPrice": 50,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "Your love for your team doesn't end when the weather changes. Smooth on the outside with unbrushed loops on the inside, our midweight French terry is breathable, making these roomy shorts comfy enough to wear all year long.",
                    "url": "https://nike.com/us/t/club-am%C3%A9rica-mens-soccer-shorts-QDdZbX/DV5184-409",
                    "imageUrl": "https://static.nike.com/a/images/t_default/9f8ad73a-dc82-4f77-bf3c-2a31ea171eba/club-am%C3%A9rica-mens-soccer-shorts-QDdZbX.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Jordan",
                    "articleNo": "FN5362-615",
                    "division": "Women",
                    "category": "Clothing",
                    "subCategory": "Lifestyle",
                    "listPrice": 150,
                    "salePrice": 127.97,
                    "currency": "USD",
                    "description": "Cardigans are best when well worn and well loved. This one is soft, relaxed and the perfect amount of broken-in, straight out the gate. With distressing along the ribbed knit, it'll look like you've had this cardigan forever.",
                    "url": "https://nike.com/us/t/jordan-womens-distressed-cardigan-m4hjBK/FN5362-615",
                    "imageUrl": "https://static.nike.com/a/images/t_default/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/1741cd42-d91e-44b1-b8c0-2501607e0fb5/jordan-womens-distressed-cardigan-m4hjBK.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Jordan",
                    "articleNo": "FN5362-045",
                    "division": "Women",
                    "category": "Clothing",
                    "subCategory": "Lifestyle",
                    "listPrice": 150,
                    "salePrice": 127.97,
                    "currency": "USD",
                    "description": "Cardigans are best when well worn and well loved. This one is soft, relaxed and the perfect amount of broken-in, straight out the gate. With distressing along the ribbed knit, it'll look like you've had this cardigan forever.",
                    "url": "https://nike.com/us/t/jordan-womens-distressed-cardigan-m4hjBK/FN5362-045",
                    "imageUrl": "https://static.nike.com/a/images/t_default/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/8dde31fc-5529-48e8-a5e3-aa974a5e376b/jordan-womens-distressed-cardigan-m4hjBK.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Milwaukee Brewers Travel Player",
                    "articleNo": "014Z03BGMZB-N0K",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 110,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "The Milwaukee Brewers Travel Player Hoodie combines sweat-wicking technology with a soft French terry lining to help keep you comfortable in cooler weather.",
                    "url": "https://nike.com/us/t/milwaukee-brewers-travel-player-mens-dri-fit-full-zip-hoodie-ZS3HWZ/014Z03BGMZB-N0K",
                    "imageUrl": "https://static.nike.com/a/images/t_default/554d93b0-1818-4b79-88c3-f272725974e2/milwaukee-brewers-travel-player-mens-dri-fit-full-zip-hoodie-ZS3HWZ.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Texas Rangers Authentic Collection Game Time",
                    "articleNo": "014G47XTER-G5B",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 90,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "This Authentic Collection Game Time Top is a lightweight garment made with double-knit fabric that helps add structure and stability. Its sweat-wicking technology and UV protection help create a breathable, functional layer for Texas Rangers game day.",
                    "url": "https://nike.com/us/t/texas-rangers-authentic-collection-game-time-mens-dri-fit-1-2-zip-long-sleeve-top-bQsgSG/014G47XTER-G5B",
                    "imageUrl": "https://static.nike.com/a/images/t_default/3704f7c5-ad30-4e86-83f9-293b87ec9ba5/texas-rangers-authentic-collection-game-time-mens-dri-fit-1-2-zip-long-sleeve-top-bQsgSG.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "USWNT 2024 Stadium Away",
                    "articleNo": "FJ4277-418",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Soccer",
                    "listPrice": 95,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "Away kit captures the brave, relentless, expressive, and creative side of the USA. The tie-dye design is a unique take of the classic red, white and blue. There is also an inner pride design that highlights the American spirit.",
                    "url": "https://nike.com/us/t/uswnt-2024-stadium-away-mens-dri-fit-soccer-replica-jersey-P0QSl9/FJ4277-418",
                    "imageUrl": "https://static.nike.com/a/images/t_default/ecde8f81-84e2-4fbd-a702-f2eeb561f1ec/uswnt-2024-stadium-away-mens-dri-fit-soccer-replica-jersey-P0QSl9.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "LSU",
                    "articleNo": "P33124J546-LSU",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 115,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "Rep LSU Baseball while looking like you just stepped off the diamond yourself in this replica baseball jersey. Team details pair with a button-down design and a classic fit to give you a look that's ready for every day, not just game day.",
                    "url": "https://nike.com/us/t/lsu-mensreplica-baseball-jersey-KCNqH6/P33124J546-LSU",
                    "imageUrl": "https://static.nike.com/a/images/t_default/c02cf06e-a11d-47a4-bb78-32a02c173eea/lsu-mensreplica-baseball-jersey-KCNqH6.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "USMNT",
                    "articleNo": "FZ0296-417",
                    "division": "Kids",
                    "category": "Clothing",
                    "subCategory": "Soccer",
                    "listPrice": 27,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "Put your national allegiance front and center in the soft feel and classic fit of this USMNT T-shirt.",
                    "url": "https://nike.com/us/t/usmnt-big-kids-soccer-t-shirt-GTwSk4/FZ0296-417",
                    "imageUrl": "https://static.nike.com/a/images/t_default/91e95c12-f9cc-42d1-8f49-ee3488b7f24f/usmnt-big-kids-soccer-t-shirt-GTwSk4.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike",
                    "articleNo": "26J613-G6U",
                    "division": "Kids",
                    "category": "Clothing",
                    "subCategory": "Lifestyle",
                    "listPrice": 44,
                    "salePrice": 27.97,
                    "currency": "USD",
                    "description": "The Nike Cargo Pants are beyond comfy. And with multiple pockets to hold small items, they are super functional too!",
                    "url": "https://nike.com/us/t/toddler-cargo-pants-mzrR8j/26J613-G6U",
                    "imageUrl": "https://static.nike.com/a/images/t_default/28f1702b-aec6-4a7d-b667-9d99ab20bf60/toddler-cargo-pants-mzrR8j.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike",
                    "articleNo": "36J613-023",
                    "division": "Kids",
                    "category": "Clothing",
                    "subCategory": "Lifestyle",
                    "listPrice": 44,
                    "salePrice": 27.97,
                    "currency": "USD",
                    "description": "The Nike Cargo Pants are beyond comfy. And with multiple pockets to hold small items, they are super functional too!",
                    "url": "https://nike.com/us/t/little-kids-woven-cargo-pants-mzrR8j/36J613-023",
                    "imageUrl": "https://static.nike.com/a/images/t_default/3a2a6cb8-ce31-40a2-ab71-9bfe7c0e5f3d/little-kids-woven-cargo-pants-mzrR8j.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike",
                    "articleNo": "36J613-G6U",
                    "division": "Kids",
                    "category": "Clothing",
                    "subCategory": "Lifestyle",
                    "listPrice": 44,
                    "salePrice": 30.97,
                    "currency": "USD",
                    "description": "The Nike Cargo Pants are beyond comfy. And with multiple pockets to hold small items, they are super functional too!",
                    "url": "https://nike.com/us/t/little-kids-woven-cargo-pants-mzrR8j/36J613-G6U",
                    "imageUrl": "https://static.nike.com/a/images/t_default/702a371c-0e67-4baf-a3aa-30990eb9a0e7/little-kids-woven-cargo-pants-mzrR8j.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike",
                    "articleNo": "26J613-023",
                    "division": "Kids",
                    "category": "Clothing",
                    "subCategory": "Lifestyle",
                    "listPrice": 44,
                    "salePrice": 27.97,
                    "currency": "USD",
                    "description": "The Nike Cargo Pants are beyond comfy. And with multiple pockets to hold small items, they are super functional too!",
                    "url": "https://nike.com/us/t/toddler-cargo-pants-mzrR8j/26J613-023",
                    "imageUrl": "https://static.nike.com/a/images/t_default/d51b38eb-f89e-47d6-aade-722b5fac83e9/toddler-cargo-pants-mzrR8j.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike Apex",
                    "articleNo": "FQ6846-010",
                    "division": "Unisex",
                    "category": "Clothing",
                    "subCategory": "Golf",
                    "listPrice": 35,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "This reversible Apex bucket hat lets you switch up your style anytime thanks to a solid color on one side and floral print graphics on the other. Lightweight and breathable, it offers 360-degree coverage to keep the sun from hitting your eyes when you're out and about.",
                    "url": "https://nike.com/us/t/apex-reversible-bucket-hat-pRlgSB/FQ6846-010",
                    "imageUrl": "https://static.nike.com/a/images/t_default/11cbd111-6efd-43ba-ab82-d4caaa6bf839/apex-reversible-bucket-hat-pRlgSB.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike Apex",
                    "articleNo": "FQ6846-133",
                    "division": "Unisex",
                    "category": "Clothing",
                    "subCategory": "Golf",
                    "listPrice": 35,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "This reversible Apex bucket hat lets you switch up your style anytime thanks to a solid color on one side and floral print graphics on the other. Lightweight and breathable, it offers 360-degree coverage to keep the sun from hitting your eyes when you're out and about.",
                    "url": "https://nike.com/us/t/apex-reversible-bucket-hat-pRlgSB/FQ6846-133",
                    "imageUrl": "https://static.nike.com/a/images/t_default/6ed0c38a-3080-41b2-9627-92b4340df20a/apex-reversible-bucket-hat-pRlgSB.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike Swim",
                    "articleNo": "NESSA703-090",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Workouts",
                    "listPrice": 46,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "You deserve a worry-free day at the pool. Made with our sweat-wicking technology and added UV protection, this athletic-style top helps you stay dry, comfortable and shielded from the sun in areas covered by the garment.",
                    "url": "https://nike.com/us/t/swim-mens-short-sleeve-hydroguard-extended-size-TxxQMV/NESSA703-090",
                    "imageUrl": "https://static.nike.com/a/images/t_default/13bbad52-1e50-49fd-a3d7-7249272370f4/swim-mens-short-sleeve-hydroguard-extended-size-TxxQMV.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike Swim",
                    "articleNo": "NESSA703-440",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Workouts",
                    "listPrice": 46,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "You deserve a worry-free day at the pool. Made with our sweat-wicking technology and added UV protection, this athletic-style top helps you stay dry, comfortable and shielded from the sun in areas covered by the garment.",
                    "url": "https://nike.com/us/t/swim-mens-short-sleeve-hydroguard-extended-size-TxxQMV/NESSA703-440",
                    "imageUrl": "https://static.nike.com/a/images/t_default/a73504f8-f6a0-42e2-b69d-cc5c0c026a57/swim-mens-short-sleeve-hydroguard-extended-size-TxxQMV.png"
                  },{
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Team 13",
                    "articleNo": "FB9833-323",
                    "division": "Unisex",
                    "category": "Clothing",
                    "subCategory": "Basketball",
                    "listPrice": 35,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "Celebrate the legacy of women’s hoops with this classic-fit tee. Made with soft cotton, it has a relaxed and casual feel perfect for repping the league you love.",
                    "url": "https://nike.com/us/t/team-13-wnba-t-shirt-JcXBMM/FB9833-323",
                    "imageUrl": "https://static.nike.com/a/images/t_default/016f3168-5137-41a8-8a31-042a685c5d5c/team-13-wnba-t-shirt-JcXBMM.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Team 13",
                    "articleNo": "FB9833-566",
                    "division": "Unisex",
                    "category": "Clothing",
                    "subCategory": "Basketball",
                    "listPrice": 35,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "Celebrate the legacy of women’s hoops with this classic-fit tee. Made with soft cotton, it has a relaxed and casual feel perfect for repping the league you love.",
                    "url": "https://nike.com/us/t/team-13-wnba-t-shirt-JcXBMM/FB9833-566",
                    "imageUrl": "https://static.nike.com/a/images/t_default/41f860a5-9ad9-490b-b875-1599f5f04f82/team-13-wnba-t-shirt-JcXBMM.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike Swim",
                    "articleNo": "NESSA703-001",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Workouts",
                    "listPrice": 46,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "You deserve a worry-free day at the pool. Made with our sweat-wicking technology and added UV protection, this athletic-style top helps you stay dry, comfortable and shielded from the sun in areas covered by the garment.",
                    "url": "https://nike.com/us/t/swim-mens-short-sleeve-hydroguard-extended-size-TxxQMV/NESSA703-001",
                    "imageUrl": "https://static.nike.com/a/images/t_default/fabb8727-1cee-4a86-8d29-c41cc7b65d84/swim-mens-short-sleeve-hydroguard-extended-size-TxxQMV.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike Dry",
                    "articleNo": "CT2682-657",
                    "division": "Kids",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 32,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "Perfect to wear on its own or as a layer, the Nike Pro Dri-FIT Top is made with stretchy fabric and sweat-wicking technology that helps keep you dry and comfortable during your workout.",
                    "url": "https://nike.com/us/t/dry-big-kids-boys-3-4-sleeve-baseball-top-6b459S/CT2682-657",
                    "imageUrl": "https://static.nike.com/a/images/t_default/43c2b2ea-a7d5-476d-961a-7c635d7ceb00/dry-big-kids-boys-3-4-sleeve-baseball-top-6b459S.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike Dry",
                    "articleNo": "CT2682-065",
                    "division": "Kids",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 32,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "Perfect to wear on its own or as a layer, the Nike Pro Dri-FIT Top is made with stretchy fabric and sweat-wicking technology that helps keep you dry and comfortable during your workout.",
                    "url": "https://nike.com/us/t/dry-big-kids-boys-3-4-sleeve-baseball-top-6b459S/CT2682-065",
                    "imageUrl": "https://static.nike.com/a/images/t_default/f63f8c29-ceff-4da3-896d-04a4928b4572/dry-big-kids-boys-3-4-sleeve-baseball-top-6b459S.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike Dry",
                    "articleNo": "CT2682-066",
                    "division": "Kids",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 32,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "Perfect to wear on its own or as a layer, the Nike Pro Dri-FIT Top is made with stretchy fabric and sweat-wicking technology that helps keep you dry and comfortable during your workout.",
                    "url": "https://nike.com/us/t/dry-big-kids-boys-3-4-sleeve-baseball-top-6b459S/CT2682-066",
                    "imageUrl": "https://static.nike.com/a/images/t_default/52005497-eeaf-4a9f-b881-0f77b5dd7c63/dry-big-kids-boys-3-4-sleeve-baseball-top-6b459S.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Nike Dry",
                    "articleNo": "CT2682-063",
                    "division": "Kids",
                    "category": "Clothing",
                    "subCategory": "Baseball",
                    "listPrice": 32,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "Perfect to wear on its own or as a layer, the Nike Pro Dri-FIT Top is made with stretchy fabric and sweat-wicking technology that helps keep you dry and comfortable during your workout.",
                    "url": "https://nike.com/us/t/dry-big-kids-boys-3-4-sleeve-baseball-top-6b459S/CT2682-063",
                    "imageUrl": "https://static.nike.com/a/images/t_default/45aa1907-deb7-47a0-9ae0-c9b9ae69d39d/dry-big-kids-boys-3-4-sleeve-baseball-top-6b459S.png"
                  },
                  {
                    "company": "NIKE",
                    "country": "USA",
                    "productName": "Javonte Williams Denver Broncos",
                    "articleNo": "67NM0B8N8WF-HZ0",
                    "division": "Men",
                    "category": "Clothing",
                    "subCategory": "Football",
                    "listPrice": 130,
                    "salePrice": null,
                    "currency": "USD",
                    "description": "Rep one of your team's top stars with this Denver Broncos Jersey. Proper ventilation and a loose fit help provide a dry, comfortable wear with the authentic look of the on-field uniform.",
                    "url": "https://nike.com/us/t/javonte-williams-denver-broncos-mens-game-football-jersey-48dpK2/67NM0B8N8WF-HZ0",
                    "imageUrl": "https://static.nike.com/a/images/t_default/00e31f3a-0e66-4658-a2f4-b3e346f9c3c5/javonte-williams-denver-broncos-mens-game-football-jersey-48dpK2.png"
                  },
      
    ];

    dispatch(setProducts(products));
};

export default productSlice.reducer;
